/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coba;

import java.awt.*;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.Transferable;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.awt.geom.*;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import javax.swing.DefaultListModel;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.TransferHandler;
import static javax.swing.TransferHandler.COPY_OR_MOVE;
import static javax.swing.TransferHandler.MOVE;
import javax.swing.border.AbstractBorder;

/**
 *
 * @author LENOVO
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    
//    class MyTransferHandler extends TransferHandler {
//
//        public int getSourceActions(JComponent c) {
//            return COPY_OR_MOVE;
//        }
//
//        protected Transferable createTransferable(JComponent c) {
//            JList l = (JList) c;
//            return new StringSelection(l.getSelectedValue().toString());
//        }
//
//        protected void exportDone(JComponent c, Transferable t, int action) {
//            if (action == MOVE) {
//                JList l = (JList) c;
//                DefaultListModel dlm = (DefaultListModel) l.getModel();
//                dlm.remove(l.getSelectedIndex());
//            }
//        }
//
//        public boolean canImport(TransferHandler.TransferSupport supp) {
//            if (!supp.isDataFlavorSupported(DataFlavor.stringFlavor)) {
//                return false;
//            }
//            return true;
//        }
//
//        public boolean importData(TransferHandler.TransferSupport supp) {
//            if (!supp.isDrop()) {
//                return false;
//            }
//            pic = (JLabel) supp.getComponent();
//            String data;
//            try {
//                data = (String) supp.getTransferable().getTransferData(DataFlavor.stringFlavor);
//            } catch (Exception e) {
//                return false;
//            }
//            listModel = (DefaultListModel) list.getModel();
//            
//            JList.DropLocation dl = (JList.DropLocation) supp.getDropLocation();
//            idx = dl.getIndex();
//            System.out.println("dx" + dl.getIndex());
//            listModel.add(idx, data);
//            idx++;
//            return true;
//
//        }
//    }
    
    public MainScreen() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        this.setBackground(new Color(0, 0, 0, 0));
        jPanel1.setBackground(new Color(0, 0, 0, 0));
//        modifyLabel();
    }

    
//    public void modifyLabel() {
//        TransferHandler th = new TransferHandler() {
//
//            @Override
//            public boolean canImport(JComponent comp, DataFlavor[] transferFlavors) {
//                return true;
//            }
//
//            @Override
//            public boolean importData(JComponent comp, Transferable t) {
//
//                try {
//                    File files = (File) t.getTransferData(DataFlavor.javaFileListFlavor);
////                    for (File file : files) {
//                        String path = new File(getClass().getResource("/image").getFile()).getAbsolutePath() + "\\" + files.getName();
//                        System.out.println(path+" yeee");
//                        dropPic.setIcon(new javax.swing.ImageIcon(path));
////                        idx++;
//
////                    }
//                } catch (UnsupportedFlavorException ex) {
//                    java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
//                } catch (IOException ex) {
//                    java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
//                }
//                return true;
//
//            }
//
//        };
//        pic.setTransferHandler(th);
//    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sizeInfoTf = new javax.swing.JTextField();
        sizeInfoShade = new javax.swing.JLabel();
        levelInfoTf = new javax.swing.JTextField();
        levelInfoShade = new javax.swing.JLabel();
        droPic = new javax.swing.JLabel();
        sepPath = new javax.swing.JSeparator();
        pathImage = new javax.swing.JTextField();
        UsageInscroll = new javax.swing.JScrollPane();
        usageInTf = new javax.swing.JTextArea();
        usageInShade = new javax.swing.JLabel();
        sepcode2 = new javax.swing.JSeparator();
        kodeSenyawa2 = new javax.swing.JTextField();
        sepname = new javax.swing.JSeparator();
        nameSenyawa = new javax.swing.JTextField();
        sepcode = new javax.swing.JSeparator();
        kodeSenyawa = new javax.swing.JTextField();
        pic = new javax.swing.JLabel();
        Usagescroll = new javax.swing.JScrollPane();
        usageTf = new javax.swing.JTextArea();
        usageShade = new javax.swing.JLabel();
        MrTf = new javax.swing.JTextField();
        MrShade = new javax.swing.JLabel();
        usageLb = new javax.swing.JLabel();
        mrLb = new javax.swing.JLabel();
        bin = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        size = new javax.swing.JLabel();
        sizeShade = new javax.swing.JLabel();
        level = new javax.swing.JLabel();
        levelShade = new javax.swing.JLabel();
        seeall = new javax.swing.JLabel();
        seeallShade = new javax.swing.JLabel();
        add = new javax.swing.JLabel();
        addShade = new javax.swing.JLabel();
        search = new javax.swing.JLabel();
        searchShade = new javax.swing.JLabel();
        title2 = new javax.swing.JLabel();
        title1 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sizeInfoTf.setEditable(false);
        sizeInfoTf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sizeInfoTf.setForeground(new java.awt.Color(189, 215, 238));
        sizeInfoTf.setBorder(null);
        sizeInfoTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeInfoTfActionPerformed(evt);
            }
        });
        jPanel1.add(sizeInfoTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, 60, 30));

        sizeInfoShade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tf mr3.png"))); // NOI18N
        jPanel1.add(sizeInfoShade, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 70, 50));

        levelInfoTf.setEditable(false);
        levelInfoTf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        levelInfoTf.setForeground(new java.awt.Color(189, 215, 238));
        levelInfoTf.setBorder(null);
        levelInfoTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                levelInfoTfActionPerformed(evt);
            }
        });
        jPanel1.add(levelInfoTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 60, 30));

        levelInfoShade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tf mr3.png"))); // NOI18N
        jPanel1.add(levelInfoShade, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 70, 50));
        jPanel1.add(droPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 110, 190, 170));

        sepPath.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(sepPath, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 210, 10));

        pathImage.setBackground(new Color(0,0,0,0));
        pathImage.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        pathImage.setForeground(new java.awt.Color(189, 215, 238));
        pathImage.setText("path gambar");
        pathImage.setBorder(null);
        pathImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathImageActionPerformed(evt);
            }
        });
        jPanel1.add(pathImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 210, 30));

        UsageInscroll.setBackground(new Color(0,0,0,0));
        UsageInscroll.setBorder(null);

        usageInTf.setBackground(new Color(32,56,100,255));
        usageInTf.setColumns(20);
        usageInTf.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        usageInTf.setForeground(new java.awt.Color(189, 215, 238));
        usageInTf.setLineWrap(true);
        usageInTf.setRows(5);
        usageInTf.setText("manfaat/sering ditemukan di...");
        usageInTf.setCaretColor(new java.awt.Color(6, 4, 52));
        usageInTf.setOpaque(true);
        UsageInscroll.setViewportView(usageInTf);

        jPanel1.add(UsageInscroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 355, 300, 70));

        usageInShade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tA usage2.png"))); // NOI18N
        jPanel1.add(usageInShade, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 330, 100));

        sepcode2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(sepcode2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 120, 10));

        kodeSenyawa2.setBackground(new Color(0,0,0,0));
        kodeSenyawa2.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        kodeSenyawa2.setForeground(new java.awt.Color(189, 215, 238));
        kodeSenyawa2.setText("kode senyawa");
        kodeSenyawa2.setBorder(null);
        kodeSenyawa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodeSenyawa2ActionPerformed(evt);
            }
        });
        jPanel1.add(kodeSenyawa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 120, 30));

        sepname.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(sepname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 120, 10));

        nameSenyawa.setBackground(new Color(0,0,0,0));
        nameSenyawa.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        nameSenyawa.setForeground(new java.awt.Color(189, 215, 238));
        nameSenyawa.setText("nama senyawa");
        nameSenyawa.setBorder(null);
        nameSenyawa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameSenyawaActionPerformed(evt);
            }
        });
        jPanel1.add(nameSenyawa, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 120, 30));

        sepcode.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(sepcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 120, 10));

        kodeSenyawa.setBackground(new Color(0,0,0,0));
        kodeSenyawa.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        kodeSenyawa.setForeground(new java.awt.Color(189, 215, 238));
        kodeSenyawa.setText("kode senyawa");
        kodeSenyawa.setBorder(null);
        kodeSenyawa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodeSenyawaActionPerformed(evt);
            }
        });
        jPanel1.add(kodeSenyawa, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 120, 30));

        pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pic2.png"))); // NOI18N
        jPanel1.add(pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, 280, -1));

        Usagescroll.setBackground(new Color(0,0,0,0));
        Usagescroll.setBorder(null);

        usageTf.setEditable(false);
        usageTf.setBackground(new Color(32,56,100,255));
        usageTf.setColumns(20);
        usageTf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        usageTf.setForeground(new java.awt.Color(189, 215, 238));
        //usageTf.setBackground(new Color(0,0,0,0));
        usageTf.setLineWrap(true);
        usageTf.setRows(5);
        //AbstractBorder brdr = new TextBubbleBorder(Color.BLACK,2,16,0);
        usageTf.setCaretColor(new java.awt.Color(6, 4, 52));
        usageTf.setOpaque(true);
        Usagescroll.setViewportView(usageTf);

        jPanel1.add(Usagescroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 405, 300, 70));

        usageShade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tA usage2.png"))); // NOI18N
        jPanel1.add(usageShade, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 390, 330, 100));

        MrTf.setEditable(false);
        MrTf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        MrTf.setForeground(new java.awt.Color(189, 215, 238));
        MrTf.setBackground(new Color(0,0,0,0));
        MrTf.setBorder(null);
        MrTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MrTfActionPerformed(evt);
            }
        });
        jPanel1.add(MrTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 350, 60, 30));

        MrShade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tf mr3.png"))); // NOI18N
        jPanel1.add(MrShade, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 340, 70, 50));

        usageLb.setBackground(new java.awt.Color(124, 131, 239));
        usageLb.setFont(new java.awt.Font("Cambria", 0, 22)); // NOI18N
        usageLb.setForeground(new java.awt.Color(6, 4, 52));
        usageLb.setText("Biasa terdapat pada:");
        usageLb.setOpaque(true);
        jPanel1.add(usageLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, -1, -1));

        mrLb.setBackground(new java.awt.Color(0, 128, 128));
        mrLb.setFont(new java.awt.Font("Cambria", 0, 22)); // NOI18N
        mrLb.setForeground(new java.awt.Color(255, 230, 153));
        mrLb.setText("Massa relatif senyawa:");
        mrLb.setOpaque(true);
        jPanel1.add(mrLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 220, -1));

        bin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/trashbin2.png"))); // NOI18N
        jPanel1.add(bin, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 510, 40, 50));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit2.png"))); // NOI18N
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 30, 30, 30));

        size.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/size2.png"))); // NOI18N
        jPanel1.add(size, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 475, 40, 30));

        sizeShade.setBackground(new Color(255,204,102,30));
        sizeShade.setForeground(new Color(255,204,102,0));
        sizeShade.setBorder(null);
        sizeShade.setMaximumSize(new java.awt.Dimension(213, 26));
        sizeShade.setMinimumSize(new java.awt.Dimension(213, 26));
        sizeShade.setOpaque(true);
        sizeShade.setPreferredSize(new java.awt.Dimension(213, 26));
        jPanel1.add(sizeShade, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 90, 40));

        level.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/level3.png"))); // NOI18N
        jPanel1.add(level, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 399, 40, 40));

        levelShade.setBackground(new Color(255,204,102,30));
        levelShade.setForeground(new Color(255,204,102,0));
        levelShade.setBorder(null);
        levelShade.setMaximumSize(new java.awt.Dimension(213, 26));
        levelShade.setMinimumSize(new java.awt.Dimension(213, 26));
        levelShade.setOpaque(true);
        levelShade.setPreferredSize(new java.awt.Dimension(213, 26));
        jPanel1.add(levelShade, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 90, 40));

        seeall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/seeall2.png"))); // NOI18N
        jPanel1.add(seeall, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 335, -1, 30));

        seeallShade.setBackground(new Color(255,204,102,30));
        seeallShade.setForeground(new Color(255,204,102,0));
        seeallShade.setBorder(null);
        seeallShade.setMaximumSize(new java.awt.Dimension(213, 26));
        seeallShade.setMinimumSize(new java.awt.Dimension(213, 26));
        seeallShade.setOpaque(true);
        seeallShade.setPreferredSize(new java.awt.Dimension(213, 26));
        jPanel1.add(seeallShade, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 90, 40));

        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add3.png"))); // NOI18N
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 265, 40, -1));

        addShade.setBackground(new Color(255,204,102,30));
        addShade.setForeground(new Color(255,204,102,0));
        addShade.setBorder(null);
        addShade.setMaximumSize(new java.awt.Dimension(213, 26));
        addShade.setMinimumSize(new java.awt.Dimension(213, 26));
        addShade.setOpaque(true);
        addShade.setPreferredSize(new java.awt.Dimension(213, 26));
        jPanel1.add(addShade, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 90, 40));

        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search2.png"))); // NOI18N
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                searchMousePressed(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 40, 40));

        searchShade.setBackground(new Color(255,204,102,30));
        searchShade.setForeground(new Color(255,204,102,0));
        searchShade.setBorder(null);
        searchShade.setMaximumSize(new java.awt.Dimension(213, 26));
        searchShade.setMinimumSize(new java.awt.Dimension(213, 26));
        searchShade.setOpaque(true);
        searchShade.setPreferredSize(new java.awt.Dimension(213, 26));
        jPanel1.add(searchShade, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 90, 40));

        title2.setFont(new java.awt.Font("Century Schoolbook", 0, 36)); // NOI18N
        title2.setForeground(new java.awt.Color(197, 224, 180));
        title2.setText("Senyawa Kimia");
        jPanel1.add(title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        title1.setFont(new java.awt.Font("Century Schoolbook", 0, 36)); // NOI18N
        title1.setForeground(new java.awt.Color(197, 224, 180));
        title1.setText("Struktur");
        jPanel1.add(title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg3.png"))); // NOI18N
        bg.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg3.png"))); // NOI18N
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 580));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 580));

        setSize(new java.awt.Dimension(1139, 575));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MrTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MrTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MrTfActionPerformed

    private void searchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMousePressed

    }//GEN-LAST:event_searchMousePressed

    private void kodeSenyawaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodeSenyawaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodeSenyawaActionPerformed

    private void nameSenyawaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameSenyawaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameSenyawaActionPerformed

    private void kodeSenyawa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodeSenyawa2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodeSenyawa2ActionPerformed

    private void pathImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathImageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pathImageActionPerformed

    private void levelInfoTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_levelInfoTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_levelInfoTfActionPerformed

    private void sizeInfoTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeInfoTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sizeInfoTfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MrShade;
    private javax.swing.JTextField MrTf;
    private javax.swing.JScrollPane UsageInscroll;
    private javax.swing.JScrollPane Usagescroll;
    private javax.swing.JLabel add;
    private javax.swing.JLabel addShade;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel bin;
    private javax.swing.JLabel close;
    private javax.swing.JLabel droPic;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField kodeSenyawa;
    private javax.swing.JTextField kodeSenyawa2;
    private javax.swing.JLabel level;
    private javax.swing.JLabel levelInfoShade;
    private javax.swing.JTextField levelInfoTf;
    private javax.swing.JLabel levelShade;
    private javax.swing.JLabel mrLb;
    private javax.swing.JTextField nameSenyawa;
    private javax.swing.JTextField pathImage;
    private javax.swing.JLabel pic;
    private javax.swing.JLabel search;
    private javax.swing.JLabel searchShade;
    private javax.swing.JLabel seeall;
    private javax.swing.JLabel seeallShade;
    private javax.swing.JSeparator sepPath;
    private javax.swing.JSeparator sepcode;
    private javax.swing.JSeparator sepcode2;
    private javax.swing.JSeparator sepname;
    private javax.swing.JLabel size;
    private javax.swing.JLabel sizeInfoShade;
    private javax.swing.JTextField sizeInfoTf;
    private javax.swing.JLabel sizeShade;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title2;
    private javax.swing.JLabel usageInShade;
    private javax.swing.JTextArea usageInTf;
    private javax.swing.JLabel usageLb;
    private javax.swing.JLabel usageShade;
    private javax.swing.JTextArea usageTf;
    // End of variables declaration//GEN-END:variables
}
